name: todo_app
description: A modern Todo application built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  supabase_flutter: ^1.6.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  google_fonts: ^6.1.0

dependency_overrides:
  sign_in_with_apple: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
